site_name: ZeroNet
site_url: https://github.com/stgapr/zeronet-Documentation-ZH_CN
site_description: 使用比特币加密技术和BT机制的去中心化网络

repo_url: https://github.com/stgapr/zeronet-Documentation-ZH_CN

extra_css: [docs.css]
extra_javascript: [docs.js]


pages:
- Introduction: "index.md"
- Frequently asked questions: "faq.md"
- Start using ZeroNet:
  - "安装": using_zeronet/installing.md
  - "网站示例": using_zeronet/sample_sites.md
  - "创建新站点": using_zeronet/create_new_site.md
- "站点开发":
  - "入门": "site_development/getting_started.md"
  - "ZeroFrame API 参考文档": "site_development/zeroframe_api_reference.md"
  - "content.json的结构": "site_development/content_json.md"
  - "dbschema.json的结构": "site_development/dbschema_json.md"
  - "授权认证": "site_development/cert_authority.md"
- "帮助ZeroNet的开发":
  - "向 ZeroNet捐助": "help_zeronet/contributing.md"
  - "网络协议": "help_zeronet/network_protocol.md"
  - "捐助": "help_zeronet/donate.md"

theme_dir: readthedocs
